# Generated by Django 3.0.2 on 2021-04-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_group', '0002_auto_20210406_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='profile_image',
            field=models.FileField(blank=True, null=True, upload_to='group'),
        ),
    ]
