# Generated by Django 3.0.2 on 2021-07-21 04:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art_group', '0007_groupfollowers_groupinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='group_member', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='GroupFollowers',
        ),
    ]
