# Generated by Django 3.0.2 on 2021-07-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_group', '0008_auto_20210721_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouppost',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
