# Generated by Django 3.0.2 on 2020-02-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_registered_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='is_connected',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'INVITED'), (3, 'RECEIVED'), (4, 'REJECTED')], default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='is_invited',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'INVITED'), (3, 'RECEIVED'), (4, 'REJECTED')], default=0),
        ),
    ]
