# Generated by Django 3.0.2 on 2020-04-28 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20200228_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source',
            field=models.PositiveSmallIntegerField(choices=[(0, 'PHONE'), (1, 'FACEBOOK'), (2, 'TWITTER'), (3, 'GMAIL')], default=0),
        ),
    ]
