# Generated by Django 3.0.2 on 2020-11-23 16:29

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_auto_20201123_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='post_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=contacts.models.post_directory_path),
        ),
    ]
