# Generated by Django 3.0.2 on 2020-11-24 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_auto_20201123_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='post_user_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
