# Generated by Django 3.0.2 on 2020-11-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_remove_comments_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
