# Generated by Django 3.0.2 on 2020-11-25 03:46

import contacts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0013_auto_20201124_1721'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(default='', max_length=200)),
                ('page_category', models.CharField(choices=[(4, 'DEFAULT'), (0, 'SPORT'), (1, 'EDUCATION'), (2, 'ORGANIZATION'), (3, 'ENTERTAINMENT')], max_length=100)),
                ('page_profile', models.ImageField(blank=True, default=None, null=True, upload_to=contacts.models.group_directory_path)),
                ('page_cover', models.ImageField(blank=True, default=None, null=True, upload_to=contacts.models.group_directory_path)),
                ('admin_name', models.CharField(default='', max_length=60)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='', max_length=200)),
                ('group_category', models.CharField(choices=[(4, 'DEFAULT'), (0, 'SPORT'), (1, 'EDUCATION'), (2, 'ORGANIZATION'), (3, 'ENTERTAINMENT')], max_length=100)),
                ('group_profile', models.ImageField(blank=True, default=None, null=True, upload_to=contacts.models.group_directory_path)),
                ('group_cover', models.ImageField(blank=True, default=None, null=True, upload_to=contacts.models.group_directory_path)),
                ('admin_name', models.CharField(default='', max_length=60)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
