# Generated by Django 3.0.2 on 2020-12-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_contact_profileid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profileId',
            field=models.IntegerField(blank=True, default=None, max_length=5000, null=True),
        ),
    ]
