# Generated by Django 3.0.2 on 2021-07-27 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_auto_20201216_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='from_request',
            field=models.IntegerField(blank=True, default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profileId',
            field=models.IntegerField(blank=True, default=None, max_length=5000),
        ),
        migrations.AlterField(
            model_name='contact',
            name='to_request',
            field=models.IntegerField(blank=True, default=None, max_length=5000),
        ),
    ]
