# Generated by Django 3.0.2 on 2021-07-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_auto_20210727_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='from_request',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='profileId',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='contact',
            name='to_request',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
