# Generated by Django 2.2.2 on 2019-06-29 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20190624_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='local_area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='terms_and_conditions',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.TextField(default='', null=True),
        ),
    ]
