# Generated by Django 2.2.4 on 2019-09-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_connection_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connections',
            field=models.IntegerField(default=0),
        ),
    ]
