# Generated by Django 2.2.4 on 2019-09-17 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_auto_20190917_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='connection_accepted',
            new_name='connection_received',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='connection_proposed',
            new_name='connection_sent',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='connection_requested',
            new_name='deal_accepted',
        ),
        migrations.AddField(
            model_name='user',
            name='deal_proposed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='deal_requested',
            field=models.IntegerField(default=0),
        ),
    ]
