# Generated by Django 3.0.2 on 2021-06-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stream_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('token', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('date_created', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='stream',
            name='channel_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='stream',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
