# Generated by Django 3.0.2 on 2021-03-11 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0002_auto_20210311_0833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('craft', models.FileField(upload_to='directory_path')),
            ],
        ),
        migrations.RemoveField(
            model_name='userart',
            name='craft',
        ),
        migrations.AddField(
            model_name='userart',
            name='art_images',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art_app.ArtImages'),
        ),
    ]
