# Generated by Django 3.0.2 on 2021-03-11 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0003_auto_20210311_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userart',
            name='art_images',
        ),
        migrations.AddField(
            model_name='artimages',
            name='user_art',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='art_app.UserArt'),
        ),
    ]
