# Generated by Django 3.0.2 on 2021-03-11 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0004_auto_20210311_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artimages',
            name='user_art',
        ),
        migrations.AddField(
            model_name='userart',
            name='art_images',
            field=models.ManyToManyField(blank=True, null=True, to='art_app.ArtImages'),
        ),
    ]
