# Generated by Django 3.0.2 on 2021-03-18 09:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art_app', '0006_userfollowers'),
    ]

    operations = [
        migrations.AddField(
            model_name='userart',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
