# Generated by Django 3.0.2 on 2021-03-18 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('art_app', '0007_userart_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('comment_user', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='userart',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, related_name='users_comment', to='art_app.ArtComment'),
        ),
    ]
