# Generated by Django 3.0.2 on 2021-05-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0008_auto_20210318_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='userart',
            name='media_type',
            field=models.CharField(default='image', max_length=100),
        ),
    ]
