# Generated by Django 3.0.2 on 2021-07-13 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art_app', '0011_usernotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userart',
            name='inspired_by',
        ),
    ]
