# Generated by Django 2.2.4 on 2019-09-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20190629_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connection_status',
            field=models.CharField(choices=[('O', 'Online'), ('F', 'Offline')], default='F', max_length=1),
        ),
    ]
