# Generated by Django 2.2.4 on 2019-09-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_user_connections'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='connections',
            new_name='connection_accepted',
        ),
        migrations.AddField(
            model_name='user',
            name='connection_proposed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='connection_requested',
            field=models.IntegerField(default=0),
        ),
    ]
