# Generated by Django 2.2.7 on 2019-12-04 10:53

import authentication.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_user_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default=None, height_field=200, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/picture/', location='/opt/apps/media/picture'), upload_to=authentication.models.user_directory_path, width_field=200),
        ),
    ]
