# Generated by Django 3.0.2 on 2020-04-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20200407_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumberotp',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='phonenumberotp',
            name='otp',
            field=models.IntegerField(default=4961),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.IntegerField(default=9708),
        ),
    ]
