# Generated by Django 3.0.2 on 2020-04-27 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20200407_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='otp',
            field=models.IntegerField(default=6443),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.IntegerField(default=6799),
        ),
        migrations.CreateModel(
            name='UserLastSeenLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'ONLINE'), (0, 'OFFLINE')], max_length=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='last_seen', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
