# Generated by Django 3.0.2 on 2020-06-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_auto_20200427_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pin_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
