# Generated by Django 3.0.2 on 2020-11-20 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_auto_20201120_0340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='phone_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
