# Generated by Django 3.0.2 on 2020-12-05 14:40

import authentication.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0028_auto_20201205_0802'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_picture',
            field=models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/picture/', location='/opt/apps/media/picture'), upload_to=authentication.models.user_directory_path),
        ),
    ]
