# Generated by Django 3.0.2 on 2020-12-30 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0029_user_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_privacy',
            field=models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVATE', 'PRIVATE')], default='PUBLIC', max_length=20),
        ),
    ]
