# Generated by Django 3.0.2 on 2021-07-07 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_user_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumberotp',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
