# Generated by Django 3.0.2 on 2021-07-21 04:38

import authentication.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0033_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_picture',
            field=models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/picture/', location='/opt/Ritesh_Office/SGSPL/Inkster/media/picture'), upload_to=authentication.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, default=None, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/picture/', location='/opt/Ritesh_Office/SGSPL/Inkster/media/picture'), upload_to=authentication.models.user_directory_path),
        ),
    ]
