# Generated by Django 3.0.2 on 2021-07-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0036_auto_20210728_0440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='github',
            new_name='twitter',
        ),
    ]
