# Generated by Django 3.0.2 on 2021-05-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrecord',
            name='account_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='paymentrecord',
            name='charge_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
