# Generated by Django 3.0.2 on 2021-06-01 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_app', '0003_stripeuseraccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(default='', max_length=2000)),
                ('transaction_id', models.CharField(default='', max_length=500)),
                ('payment_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_from', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
