# Generated by Django 3.0.2 on 2021-06-01 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_app', '0005_auto_20210601_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenthistory',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
    ]
