# Generated by Django 3.0.2 on 2021-03-14 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0031_user_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
